// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v6.33.1
// source: proto/bot.proto

package bot

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type SendUpdateRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Url           string                 `protobuf:"bytes,2,opt,name=url,proto3" json:"url,omitempty"`
	Description   string                 `protobuf:"bytes,3,opt,name=description,proto3" json:"description,omitempty"`
	TgChatIds     []int64                `protobuf:"varint,4,rep,packed,name=tg_chat_ids,json=tgChatIds,proto3" json:"tg_chat_ids,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SendUpdateRequest) Reset() {
	*x = SendUpdateRequest{}
	mi := &file_proto_bot_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SendUpdateRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SendUpdateRequest) ProtoMessage() {}

func (x *SendUpdateRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_bot_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SendUpdateRequest.ProtoReflect.Descriptor instead.
func (*SendUpdateRequest) Descriptor() ([]byte, []int) {
	return file_proto_bot_proto_rawDescGZIP(), []int{0}
}

func (x *SendUpdateRequest) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *SendUpdateRequest) GetUrl() string {
	if x != nil {
		return x.Url
	}
	return ""
}

func (x *SendUpdateRequest) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *SendUpdateRequest) GetTgChatIds() []int64 {
	if x != nil {
		return x.TgChatIds
	}
	return nil
}

type SendUpdateResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SendUpdateResponse) Reset() {
	*x = SendUpdateResponse{}
	mi := &file_proto_bot_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SendUpdateResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SendUpdateResponse) ProtoMessage() {}

func (x *SendUpdateResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_bot_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SendUpdateResponse.ProtoReflect.Descriptor instead.
func (*SendUpdateResponse) Descriptor() ([]byte, []int) {
	return file_proto_bot_proto_rawDescGZIP(), []int{1}
}

var File_proto_bot_proto protoreflect.FileDescriptor

const file_proto_bot_proto_rawDesc = "" +
	"\n" +
	"\x0fproto/bot.proto\x12\x03bot\"w\n" +
	"\x11SendUpdateRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12\x10\n" +
	"\x03url\x18\x02 \x01(\tR\x03url\x12 \n" +
	"\vdescription\x18\x03 \x01(\tR\vdescription\x12\x1e\n" +
	"\vtg_chat_ids\x18\x04 \x03(\x03R\ttgChatIds\"\x14\n" +
	"\x12SendUpdateResponse2K\n" +
	"\n" +
	"BotService\x12=\n" +
	"\n" +
	"SendUpdate\x12\x16.bot.SendUpdateRequest\x1a\x17.bot.SendUpdateResponseBXZVgitlab.education.tbank.ru/backend-academy-go-2025/homeworks/link-tracker/pkg/proto/botb\x06proto3"

var (
	file_proto_bot_proto_rawDescOnce sync.Once
	file_proto_bot_proto_rawDescData []byte
)

func file_proto_bot_proto_rawDescGZIP() []byte {
	file_proto_bot_proto_rawDescOnce.Do(func() {
		file_proto_bot_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_bot_proto_rawDesc), len(file_proto_bot_proto_rawDesc)))
	})
	return file_proto_bot_proto_rawDescData
}

var file_proto_bot_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_proto_bot_proto_goTypes = []any{
	(*SendUpdateRequest)(nil),  // 0: bot.SendUpdateRequest
	(*SendUpdateResponse)(nil), // 1: bot.SendUpdateResponse
}
var file_proto_bot_proto_depIdxs = []int32{
	0, // 0: bot.BotService.SendUpdate:input_type -> bot.SendUpdateRequest
	1, // 1: bot.BotService.SendUpdate:output_type -> bot.SendUpdateResponse
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_proto_bot_proto_init() }
func file_proto_bot_proto_init() {
	if File_proto_bot_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_bot_proto_rawDesc), len(file_proto_bot_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_bot_proto_goTypes,
		DependencyIndexes: file_proto_bot_proto_depIdxs,
		MessageInfos:      file_proto_bot_proto_msgTypes,
	}.Build()
	File_proto_bot_proto = out.File
	file_proto_bot_proto_goTypes = nil
	file_proto_bot_proto_depIdxs = nil
}
